# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

matrix:
    include:
      - compiler: gcc
        env: |
          USER_CONFIG="using gcc : : g++-4.8 --std=c++03 -fsanitize=address ;"
          BOOST_VERSION=1.64.0
          BOOST_FILENAME=boost_1_64_0
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ --std=c++11 -fsanitize=address ;"
          BOOST_VERSION=1.64.0
          BOOST_FILENAME=boost_1_64_0

before_script:
    - cd ${HOME}
    - echo $USER_CONFIG > user-config.jam
    - cat user-config.jam
    - export BOOST_ROOT=${HOME}/boost
    - |
        mkdir $HOME/download
        mkdir $HOME/extract
        cd $HOME/download
        if [ "$TRAVIS_EVENT_TYPE" == cron ]
        then
            echo "Downloading snapshot"
            curl https://api.bintray.com/packages/boostorg/master/snapshot/files |
                python -c "import os.path, sys, json; x = json.load(sys.stdin); print '\n'.join(a['path'] for a in x if os.path.splitext(a['path'])[1] == '.bz2')" |
                head -n 1 |
                sed 's/^/wget -O boost.tar.bz2 http:\/\/dl.bintray.com\/boostorg\/master\//' |
                bash
        else
            echo "Downloading ${BOOST_FILENAME}"
            wget -O boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/${BOOST_FILENAME}.tar.bz2/download
        fi
        cd $HOME/extract
        tar -xjf $HOME/download/boost.tar.bz2
        mv * ${BOOST_ROOT}
    - cd $HOME
    - rm -r ${BOOST_ROOT}/tools/quickbook
    - mv ${TRAVIS_BUILD_DIR} ${BOOST_ROOT}/tools/quickbook
    - cd ${BOOST_ROOT}/tools/build
    - mkdir ${HOME}/opt
    - ./bootstrap.sh
    - ./b2 install --prefix=$HOME/opt

script:
    - cd ${BOOST_ROOT}/tools/quickbook
    - ${HOME}/opt/bin/b2 dist-bin
    - cd ${BOOST_ROOT}/tools/quickbook/test
    - ${HOME}/opt/bin/b2
    - cd ${BOOST_ROOT}/tools/quickbook/test/python
    - python run_tests.py ${BOOST_ROOT}/dist/bin/quickbook
